<?php
// $Id$

/**
 * @file
 * Feeds Fetcher for ARTstor Shared Shelf API
 */

/**
 * Implements hook_feeds_plugins().
 */
function sharedshelffetcher_feeds_plugins() {
  $info = array();
  $info['sharedshelffetcher_fetcher'] = array(
    'name' => 'Feeds Fetcher for Shared Shelf',
    'description' => 'Fetches feeds files from Shared Shelf.',
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'sharedshelffetcher_fetcher',
      'file' => 'sharedshelffetcher_fetcher.inc',
      'path' => drupal_get_path('module', 'sharedshelffetcher'),
    ),
  );
  return $info;
}

/**
 * Implements hook_enable().
 */
function sharedshelffetcher_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
